### PR TITLE
FIX: Graph nodes should not be duplicated (fixes #280).

### LINKED ISSUE #280: Graph nodes should not be duplicated
For now, when the user bookmarked a document AND is one of its editors, the node is duplicated.

Image

### PR DESCRIPTION
**Pull request by CocoChart**
I, Corentin Chartier, hereby grant to Hyperglosae maintainers the right to publish my contribution under the terms of any licenses the Free Software Foundation classifies as Free Software Licenses.

### CODE REVIEW

File: frontend/src/routes/Bookshelf.jsx [hunk 1]
```diff
@@ -22,6 +22,7 @@ function Bookshelf({ backend, user }) {
   }, [lastUpdate, user, backend]);
   const docs = documents?.filter(x => !!x)
     .map(({_id, dc_title, links}) => [_id, dc_title, links]);
+  const uniqueDocs = Array.from(new Map(docs.map(doc => [doc[0], doc])).values());
```
Comment (benel) [inline frontend/src/routes/Bookshelf.jsx:25]: It it is not neccessary to create a new constant... Moreover this means that displayedDocs will not benefit from this deduplication.

Keeping the same idea (of using `Map()`) you could squash the lines 23-25 into a single one:

```js
const docs = [
  ...new Map(
    documents?.filter(x => !!x)
      .map(({_id, dc_title, links}) => [_id, [_id, dc_title, links]]
  ).values()
];
```

**Review by benel — CHANGES_REQUESTED** [review]

File: frontend/src/routes/Bookshelf.jsx [hunk 2]
```diff
@@ -30,7 +31,7 @@ function Bookshelf({ backend, user }) {
         return (
           <Row>
             <Col className="col-10">
-              <Graph rawDocs={docs} {...{displayedDocs}} />
+              <Graph rawDocs={uniqueDocs} {...{displayedDocs}} />
```
Comment (benel) [inline frontend/src/routes/Bookshelf.jsx:34]: And then `uniqueDocs` will be `docs` again.

**Review by benel — APPROVED** [review]
