### PR TITLE
FIX: License should not be displayed with other metadata (fixes #140)...

### LINKED ISSUE #140: Content license should not be displayed with other metadata...
... but with the content itself.

The problem is information overload.

Please note, that the development could be split into:
- a refactoring commit so that License could be a reusable component (`REFACTORING: License component should be reusable.`),
- a fix commit to change its position in the document (`FIX: Content license should not be displayed with other metadata...⮐but with the content itself.`).

### PR DESCRIPTION
**Pull request by Nizreenana**
I, Ana, hereby grant to Hyperglosae maintainers the right to publish our contribution under the terms of any licenses the Free Software Foundation classifies as Free Software Licenses.

### CODE REVIEW

File: frontend/src/routes/Lectern.js [hunk 1]
```diff
@@ -145,13 +149,14 @@ function Rubric({id}) {
...
 
-function PassageMargin({active, scholium, rubric, backend}) {
+function PassageMargin({active, scholium, rubric, backend, metadata, length, index}) {
   if (!active) return;
   return (
     <Col xs={5} className="scholium">
       {scholium.map((x, i) =>
         <EditableText key={i} text={x.text} id={x.id} {...{rubric, backend}} />
       )}
+      {index === length - 1 && <License key={metadata} license={metadata} />}
```
Comment (benel) [inline frontend/src/routes/Lectern.js:159]: Pass only license as a parameter.

File: frontend/src/components/License.js [hunk 2]
```diff
@@ -0,0 +1,37 @@
+import React, { useState, useEffect } from 'react';
+
+function License({ license }) {
+  const [license_uri, setLicense_uri] = useState(null);
+
+  useEffect(() => {
+    if (license && license.dc_license) {
```
Comment (benel) [inline frontend/src/components/License.js:7]: The parameter should be already `license` rather than `metadata`.

File: frontend/src/components/License.js [hunk 3]
```diff
@@ -0,0 +1,37 @@
+import React, { useState, useEffect } from 'react';
+
+function License({ license }) {
+  const [license_uri, setLicense_uri] = useState(null);
+
+  useEffect(() => {
```
Comment (benel) [inline frontend/src/components/License.js:6]: `useEffect` is not necessary since everything is in the property.

File: frontend/src/components/License.js [hunk 4]
```diff
@@ -0,0 +1,37 @@
+import React, { useState, useEffect } from 'react';
+
+function License({ license }) {
+  const [license_uri, setLicense_uri] = useState(null);
```
Comment (benel) [inline frontend/src/components/License.js:4]: `useState` is not necessary since everything is in the property.

File: frontend/src/components/License.js [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+    }
+  }, [license]);
+
+  let license_name;
+  if (license_uri) {
+    const match = /BY[\w-]+/i.exec(license_uri);
+    license_name = match ? match[0] : 'unknown';
+  }
+
+  if (!license) {
```
Comment (benel) [inline frontend/src/components/License.js:20]: Is it necessary?
If yes, it should be tested.

File: frontend/src/components/License.js [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+      setLicense_uri(license.dc_license);
+    } else {
+      setLicense_uri(null); // Explicitly set to null when no license is present
+    }
+  }, [license]);
+
+  let license_name;
+  if (license_uri) {
+    const match = /BY[\w-]+/i.exec(license_uri);
+    license_name = match ? match[0] : 'unknown';
```
Comment (benel) [inline frontend/src/components/License.js:17]: Is it necessary?
If yes, it should be tested.
Maybe as a separate fix.

File: frontend/src/components/Metadata.js [hunk 7]
```diff
@@ -38,7 +38,6 @@ function Metadata({metadata = {}, editable, backend}) {
 
   let format = (actors, prefix = '', suffix = '') =>
     actors && (prefix + [actors].flat().join(' & ') + suffix);
-
```
Comment (benel) [inline frontend/src/components/Metadata.js:41]: Unrelated with the issue.

File: frontend/src/routes/Lectern.js [hunk 8]
```diff
@@ -118,7 +121,7 @@ function Lectern({backend}) {
   );
 }
 
-function Passage({source, rubric, scholia, margin, backend}) {
+function Passage({source, rubric, scholia, margin, backend, sourceMetadata, metadata, length, index}) {
```
Comment (benel) [inline frontend/src/routes/Lectern.js:124]: The license should not be in a passage but in the lectern.

File: frontend/src/routes/Lectern.js [hunk 9]
```diff
@@ -145,13 +149,14 @@ function Rubric({id}) {
   );
 }
 
-function PassageMargin({active, scholium, rubric, backend}) {
+function PassageMargin({active, scholium, rubric, backend, metadata, length, index}) {
```
Comment (benel) [inline frontend/src/routes/Lectern.js:152]: The license should not be in a passage but in the lectern.

**Review by benel — CHANGES_REQUESTED** [review]
Thank you very much for your contribution, Ana.
Here are several request changes.

**Review by benel — APPROVED** [review]
